### ISSUE TITLE
":proxy" Does Not Exist

### ISSUE THREAD

**Issue by kp-jonathan-pustelnik** [vmware-samples/euc-samples#264]
Default   1874     hubd: [com.vmware.hub.workflows:Scripts] Script (macOS Updater Utility) execution result = Failure , reason = Print: Entry, ":proxy", Does Not Exist
![Image 29-01-2023 at 14 31](https://user-images.githubusercontent.com/108396241/215327742-78cd8850-e1c9-444b-8c6e-5eb05cf9344a.jpeg)
![Image 29-01-2023 at 15 00](https://user-images.githubusercontent.com/108396241/215327829-f458d94c-54d7-4cb4-bc81-3c02c1e54584.jpeg)

**Comment by ThePirat91** [comment]
Hello, it has been fixed on rev. 10.1

https://github.com/vmware-samples/euc-samples/pull/261

**Comment by kp-jonathan-pustelnik** [comment]
@ThePirat91 Tried copying the new file but that still dont work.
Generating the same error.
Should I modify anything?

**Comment by ThePirat91** [comment]
Are you sure you are using the new script version?
Try to compare the section "#grab proxy info" of your published script with the one hosted on the github repo.
Next, try to start from scratch on WS1 (delete the published script and assignment and start the process again).

Regards

**Comment by kp-jonathan-pustelnik** [comment]
So that actually worked well, removing the current script and creating a new one worked and it was executed.
Thought it was executed the windows that was suppose to pop up with "Upgrade" is not popping @ThePirat91

**Comment by mzaske3** [comment]
As @ThePirat91 pointed out this is fixed in the latest revision 10 that is available.
